version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow -d taskflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  taskflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskflow
      DB_USERNAME: taskflow
      DB_PASSWORD: taskflow123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  taskflow-network:
    driver: bridge