spring:
  application:
    name: taskflow-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration-hours: ${JWT_EXPIRATION_HOURS:24}