spring:
  application:
    name: taskflow-api
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info