spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskflow}
    username: ${DB_USERNAME:taskflow}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
      '[hibernate.format_sql]': true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    '[com.rhenan.taskflow]': INFO
    '[org.springframework.web]': WARN
    '[org.hibernate]': WARN
