spring:
  application:
    name: taskflow-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:taskflow}
    username: ${DB_USERNAME:taskflow}
    password: ${DB_PASSWORD:taskflow123}
    driver-class-name: org.postgresql.Driver


  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
      '[hibernate.format_sql]': false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://jaeger:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    '[com.rhenan.taskflow]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.boot.actuate]': DEBUG
    '[org.hibernate]': WARN
    '[org.flywaydb]': INFO
    '[io.opentelemetry]': DEBUG
    '[io.micrometer.tracing]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"