spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.H2Dialect
    show-sql: false
  flyway:
    enabled: false
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: false