spring:
  datasource:
    url: jdbc:h2:mem:taskflow;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true