name: Code Quality (Qodana)

on:
  pull_request:
    branches: [ 'release' ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  security-events: write

concurrency:
  group: qodana-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: true
          use-caches: true
          use-annotations: true
          post-pr-comment: false
          upload-result: true